"""Free functions for sustainability analysis over an sOCEL."""

from socel.analysis.allocation import (
    AllocationParameters,
    AllocationResult,
    CarriedQuantityResult,
    FlowAllocation,
    FlowCarriedQuantity,
    FlowEventQuantity,
    FlowSelection,
    HandlingUnitQuantity,
    LineageDefinition,
    allocate,
    carry,
    event_quantities,
)
from socel.analysis.attribution import (
    AttributionResult,
    AttributionScope,
    EventAttribution,
    attribute,
)
from socel.analysis.impact import (
    AllocatedImpactResult,
    EventImpact,
    EventImpactResult,
    HandlingUnitImpact,
    ImpactFactors,
    ProductFootprintResult,
    impact_allocations,
    impact_events,
    impact_quantity,
    product_footprints,
)
from socel.analysis.quantification import AnalysisWindow, quantity, share

__all__ = [
    "AllocatedImpactResult",
    "AllocationParameters",
    "AllocationResult",
    "AnalysisWindow",
    "AttributionResult",
    "AttributionScope",
    "CarriedQuantityResult",
    "EventAttribution",
    "EventImpact",
    "EventImpactResult",
    "FlowAllocation",
    "FlowCarriedQuantity",
    "FlowEventQuantity",
    "FlowSelection",
    "HandlingUnitImpact",
    "HandlingUnitQuantity",
    "ImpactFactors",
    "LineageDefinition",
    "ProductFootprintResult",
    "allocate",
    "attribute",
    "carry",
    "event_quantities",
    "impact_allocations",
    "impact_events",
    "impact_quantity",
    "product_footprints",
    "quantity",
    "share",
]
